export class UpdateMalzemeDto {
  kod?: string
  ad?: string
  kullanimda?: boolean
  tip?: number
  malzemeTuru?: string
  tipi?: string
  kategori?: string
  pluKodu?: string
  rafOmru?: number
  rafOmruBirim?: string
  sezon?: string
  markaId?: number
  model?: string
  kdvGenel?: string
  kdvPerakende?: string
  kdvToptan?: string
  kdvPSatisIade?: string
  kdvTSatisIade?: string
  ekVergiTanimi?: string
  tevkifatSatinAlmaPay?: number
  tevkifatSatinAlmaPayda?: number
  tevkifatSatisPay?: number
  tevkifatSatisPayda?: number
  kullanimYeri?: string
  takipSekli?: string
  ureticiFirmaKodu?: string
  ureticiUrunKodu?: string
  isoDokumanNo?: string
  gtipNo?: string
  webSayfasi?: string
  kampanyaGrubu?: string
  grupId?: number
  fiyatGrubu?: string
  operasyonKodu?: string
  kumasTuruId?: number
  numaratorId?: number
  cinsi?: string
  renk?: string
  grm2?: number
  ebat?: string
  ozellik1?: string
  ozellik2?: string
  ozellik3?: string
  ozellik4?: string
  derece?: string
  enOlcu?: string
  boyOlcu?: string
  kapak?: string
  micron?: string
  en?: number
  boy?: number
  iplikBoyali?: boolean
  ormeTipi?: string
  kumasUretimTipi?: string
  hesapBirimi?: string
  iplikNoId?: number
  iplikCinsiId?: number
  organik?: boolean
  iplikKompozisyonId?: number
}
