ALTER TABLE malzeme ADD en_olcu VARCHAR(100) NULL;
ALTER TABLE malzeme ADD boy_olcu VARCHAR(100) NULL;
ALTER TABLE malzeme ADD kapak VARCHAR(100) NULL;
ALTER TABLE malzeme ADD micron VARCHAR(100) NULL;
